CloudJ/CloudJ.Client/Controllers/CollectionController.cs
using CloudJ.Client.Clients;
using CloudJ.Client.Models;
using CloudJ.Contracts.DTOs.CollectionDtos;
using CloudJ.Contracts.DTOs.SolutionDtos.Photo;
using CloudJ.Contracts.DTOs.SolutionDtos.Solution;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CloudJ.Client.Controllers
{
    [Controller]
    [Route("[controller]")]
    public class CollectionController : Controller
    {
        private readonly ISolutionApiClient _solutionApiClient;
        private readonly ICollectionApiClient _collectionApiClient;
        public CollectionController(ISolutionApiClient solutionApiClient, ICollectionApiClient collectionApiClient)
        {
            _solutionApiClient = solutionApiClient;
            _collectionApiClient = collectionApiClient;
        }

        [HttpGet]
        public async Task<IActionResult> AddCollection()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddCollection(NewCollectionModel dto)
        {
            var new_col = new NewCollectionDto
            {
                Name = dto.Name,
                Description = dto.Description,
                Preview = dto.Preview
            };

            var ph = dto.PhotoPreview;
            byte[] p1 = null;
            using (var fs1 = ph.OpenReadStream())
            using (var ms1 = new MemoryStream())
            {
                fs1.CopyTo(ms1);
                p1 = ms1.ToArray();
            }

            new_col.PhotoPreview = new NewPhotoDto { Data = p1, Type = "Logo" };
            var response = await _collectionApiClient.AddCollectionAsync(new_col);
            return Redirect($"~/Collection/AddCollectionSol?id={response.Data.Id}");
        }

        [HttpGet]
        [Route("addCollectionSol")]
        public async Task<IActionResult> AddCollectionSol(long id)
        {
            var response = await _collectionApiClient.GetByFilterAsync(new CollectionFilter { Id = id });
            ViewBag.Solutions = response.Data.FirstOrDefault().Solutions;
            return View(new CollectionSolModel { CollectionId = id});

        }

        [HttpPost]
        [Route("addCollectionSol")]
        public async Task<IActionResult> AddCollectionSol(CollectionSolModel model)
        {
            var currentCollection = await _collectionApiClient.GetByFilterAsync(new CollectionFilter { Id = model.CollectionId });

            var truncSols = currentCollection.Data.FirstOrDefault().Solutions.ToList();
            truncSols.Add(new TruncSolutionDto { SolutionId = model.SolutionId });

            var otvet= await _collectionApiClient.UpdateCollectionAsync(new UpdateCollectionDto {Id= model.CollectionId, Solutions = truncSols });
            //ViewBag.Solutions = response.Data.FirstOrDefault().Solutions;
            return Ok(otvet);



        }

        [HttpGet]
        [Route("collectionEdit")]
        public async Task<IActionResult> EditCollection(long id)
        {
            return View();
        }

        /// <summary>
        /// Получение информации о выборке
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("get/{id}")]
        public async Task<IActionResult> GetCollectionInfo(int id)
        {
            var col = await _collectionApiClient.GetByFilterAsync(new CollectionFilter { Id = id});
            var model = col.Data;



            List<SolutionDto> slist = new List<SolutionDto>();

            foreach(TruncSolutionDto t in model.First().Solutions)
            {
                var tempResponse = await _solutionApiClient.GetByFilterAsync(new SolutionFilter { SolutionId = t.SolutionId });
                slist.Add(tempResponse.Data.FirstOrDefault());
                    
                    
                    
            }

            ViewBag.Solutions = slist;

            return View(model.First());
        }
    }
}

CloudJ/CloudJ.Client/Views/Collection/AddCollection.cshtml
@{
    ViewData["Title"] = "AddCollection";
}

@model CloudJ.Client.Models.NewCollectionModel

    <form method="post" asp-controller="Collection" asp-action="AddCollection" enctype="multipart/form-data">
        <section class="intro intro__marg">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p class="add-sel-title">Добавление подборки</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-5">

                        <fieldset>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Название</label>
                                <input asp-for="Name" type="text" class="form-control" id="exampleInputEmail1"
                                       aria-describedby="emailHelp" placeholder="Введите название плана">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Слоган</label>
                                <input asp-for="Preview" type="text" class="form-control" id="exampleInputEmail1"
                                       aria-describedby="emailHelp" placeholder="Введите название плана">
                            </div>
                        </fieldset>

                    </div>
                    <div class="col-lg-12">


                        <fieldset>
                            <div class="form-group">
                                <label for="exampleTextarea">Содержание</label>
                                <textarea asp-for="Description" class="form-control" id="exampleTextarea" rows="10"
                                          style="overflow-y: scroll;"></textarea>
                            </div>


                            <div class="form-group">



                                <label for="prew">Лагатип</label>
                                <input asp-for="PhotoPreview" type="file" id="prew" value="" />



                            </div>



                            <button type="submit" class="btn btn-primary rounded-0" style="width: 100%;">Добавить</button>

                        </fieldset>

                    </div>
                   
                </div>
            </div>
        </section>
    </form>

CloudJ/CloudJ.Client/Views/Collection/AddCollectionSol.cshtml
@{
    ViewData["Title"] = "AddCollectionSol";
}

@using CloudJ.Contracts.DTOs.CollectionDtos

@model CloudJ.Client.Models.CollectionSolModel

<form method="post" asp-controller="Collection" asp-action="AddCollectionSol">

    <fieldset>
        <input asp-for="CollectionId" hidden="true" value="@Model.CollectionId" />
        <div class="form-group">
            <label for="exampleInputEmail1">Id решения</label>
            <input asp-for="SolutionId" type="number" class="form-control" id="exampleInputEmail1"
                   aria-describedby="emailHelp" placeholder="Введите id решения">
        </div>

        <button type="submit" class="btn btn-primary rounded-0" style="width: 100%;">Добавить</button>


    </fieldset>


</form>







<h2 for="exampleInputPassword1" style="margin-top: 10px;">Список всех id решений</h2>
<table>
    <colgroup>
        <col span="2">
        <col>
    </colgroup>
    <tr>

        <th>Id решения</th>

    </tr>
    @foreach (TruncSolutionDto s in ViewBag.Solutions)
    {
        <tr>
            
            <td>@s.SolutionId</td>
        </tr>
    }
</table>

CloudJ/CloudJ.Client/Views/Collection/EditCollection.cshtml
@{
    ViewData["Title"] = "EditCollection";
}

<section class="intro intro__marg">
    <div class="container">
        <div class="row">

            <div class="col-lg-3">
                <h1>Коллекции</h1>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="btn__img">
                    <img src="~/img/collections1.png" alt="collections1" class="margin__top30px">
                    <form>
                        <button class="btn"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                    </form>
                </div>
                <div class="btn__img">

                    <img src="~/img/collections2.png" alt="collections2" class="margin__top30px">
                    <form>
                        <button class="btn"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                    </form>
                </div>
                <div class="btn__img">
                    <img src="~/img/collections1.png" alt="collections1" class="margin__top30px">
                    <form>
                        <button class="btn"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                    </form>
                </div>
            </div>
            <div class="col-lg-6">
                <form method="get" asp-controller="Collection" asp-action="AddCollection">
                    <button class="btn new__collections rounded-0 margin__top30px" type="submit">
                        Новая подборка
                        +
                    </button>
                </form>
            </div>

        </div>
    </div>
</section>

CloudJ/CloudJ.Client/Views/Collection/GetCollectionInfo.cshtml
@{
    ViewData["Title"] = "GetCollectionInfo";
}

@model CloudJ.Contracts.DTOs.CollectionDtos.CollectionDto
@using CloudJ.Contracts.DTOs.SolutionDtos.Solution

<div class="container">
    <div class="row">
        <p class="col-lg-12 db">@Model.Name</p>
       
    </div>
    <div class="row">
        <div class="col-lg-9 selection-bottom-text">
            
            @Model.Description

        </div>



        <div class="col-lg-3">



            @foreach(SolutionDto s in ViewBag.Solutions){
            <div class="row">
                <div class="col-lg-12 product">
                    <div class="media">
                        <div class="media-body">
                            <h5 class="mt-3 mb-1 product__h5">@s.Name</h5>
                        </div>
                        @*<img src="~/img/Large.png" class="mt-3 product__img" alt="Large">*@
                        @{
                            byte[] logo = s.Photos.Where(p => p.Type.Equals("Logo")).FirstOrDefault()?.Data;
                        }
                        @if (logo != null)
                        {
                            <img src="data:image/jpeg;base64,@Convert.ToBase64String(logo)" style="width: 40px" class="mt-1 product__img" alt="Large">
                        }
                        else
                        {
                            <img src="~/img/DB.png" style="width: 40px" class="mt-1 product__img" alt="Large">

                        }
                    </div>
                    <p class="product__p" style="word-break: break-all;">
                        @if (s.Description.Length > 150)
                        {
                            @Html.Raw(s.Description.Substring(0, 150) + "...").ToString()
                        }
                        else
                        {
                            @Html.Raw(s.Description).ToString()
                        }
                    </p>
                    <p class="product__p">Рейтинг: @s.Rate.0</p>

                    @if (s.Plans.Any())
                    {
                        <p class="product__p">Стоимость: от @s.Plans?.FirstOrDefault()?.Price р.</p>
                    }
                    <a href="page_product.html" class="buy">Получить</a>

                </div>
            </div>
            }

        </div>    </div>

</div>
    </div>