CloudJ/CloudJ.Client/Controllers/ProductController.cs
using CloudJ.Client.Clients;
using CloudJ.Client.Models;
using CloudJ.Contracts.DTOs.SolutionDtos.Category;
using CloudJ.Contracts.DTOs.SolutionDtos.Cloud;
using CloudJ.Contracts.DTOs.SolutionDtos.Photo;
using CloudJ.Contracts.DTOs.SolutionDtos.Plan;
using CloudJ.Contracts.DTOs.SolutionDtos.Review;
using CloudJ.Contracts.DTOs.SolutionDtos.Solution;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CloudJ.Client.Controllers
{
    [Controller]
    [Route("[controller]")]
    public class ProductController : Controller
    {
        private readonly ISolutionApiClient _solutionApiClient;
        private readonly IBillingApiClient _billingApiClient;
        private readonly IIdentityClient _identityClient;
        public ProductController(ISolutionApiClient solutionApiClient, IBillingApiClient billingApiClient, IIdentityClient identityClient)
        {
            _solutionApiClient = solutionApiClient;
            _billingApiClient = billingApiClient;
            _identityClient = identityClient;
            
        }

        /// <summary>
        /// Страница конкретного решения
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("{id:long}")]
        public async Task<IActionResult> GetProductById(long id)
        {
            var response = await _solutionApiClient.GetByFilterAsync(new SolutionFilter
            {
                SolutionId = id
            });
            var dto = response.Data.FirstOrDefault();

            if (dto.Reviews.Any())
            {
                IDictionary<string, string> id_name = new Dictionary<string, string>();
                foreach(ReviewDto rd in dto.Reviews)
                {
                    if (id_name.ContainsKey(rd.AuthorId))
                        continue;

                    var user = await _identityClient.GetUserInfoAsync(rd.AuthorId);
                    var userData = user.Data;

                    if (userData != null)
                        id_name.Add(rd.AuthorId, userData.Email);
                    else
                        id_name.Add(rd.AuthorId, "User deleted");

                }
                ViewBag.ReviewAuthors = id_name;

            }

            return View(dto);
        }

        /// <summary>
        /// Добавление отзыва к решению
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("id:long")]
        public async Task<IActionResult> AddReview(NewReviewDto dto)
        {
            dto.AuthorId = User.Claims.FirstOrDefault(c => c.Type.Contains("nameidentifier")).Value;
            var result = await _solutionApiClient.AddReviewAsync(dto);
            return Redirect($"~/Product/{dto.SolutionId}");

        }

        /// <summary>
        /// Добавить ссылку к решению
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("links")]
        public async Task<IActionResult> AddLink([FromQuery]long id)
        {
            var solution = await _solutionApiClient.GetByFilterAsync(new SolutionFilter { SolutionId = id });
            ViewBag.Links = solution.Data.FirstOrDefault().SolutionLinks;
            return View(new NewSolutionLinkDto { SolutionId = id});
        }

        /// <summary>
        /// Запрос к апи на добавление ссылки решения
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("links")]
        public async Task<IActionResult> AddLink(NewSolutionLinkDto dto)
        {
            var response = await _solutionApiClient.AddSolutionLinkAsync(dto);
            var solution = await _solutionApiClient.GetByFilterAsync(new SolutionFilter { SolutionId = dto.SolutionId});
            ViewBag.Links = solution.Data.FirstOrDefault().SolutionLinks;
            return View(dto);
        }
        /// <summary>
        /// Запрос к апи на удаление ссылки
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("deleteLink")]
        public async Task<IActionResult> DeleteLink(RemoveSolutionLinkDto dto)
        {
            var response = await _solutionApiClient.RemoveSolutionLinkAsync(dto);
            return Redirect($"~/Product/links?id={dto.SolutionId}");
        }

        /// <summary>
        /// Страница добавления плана
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("plan")]
        public async Task<IActionResult> AddPlan([FromQuery]long id)
        {
            var response = await _solutionApiClient.GetByFilterAsync(new SolutionFilter { SolutionId = id});
            ViewBag.Plans = response.Data.FirstOrDefault().Plans;
            return View(new NewPlanDto { SolutionId = id });
        }

        /// <summary>
        /// Запрос к апи на добавление плана к решению
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("plan")]
        public async Task<IActionResult> AddPlan(NewPlanDto dto)
        {
            var response = await _solutionApiClient.AddSolutionPlanAsync(dto);
            var sols = await _solutionApiClient.GetByFilterAsync(new SolutionFilter { SolutionId = dto.SolutionId });
            ViewBag.Plans = sols.Data.FirstOrDefault().Plans;
            return View(dto);
        }

        /// <summary>
        /// Добавить решение(первая форма с выбором докера или нашей спецификации)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("add")]
        public async Task<IActionResult> AddSolution()
        {
            return View();
        }

        /// <summary>
        /// Страница добавления по нашей спецификации
        /// </summary>
        /// <returns></returns>
        [Authorize]
        [HttpGet]
        [Route("addPersonalPanel")]
        public async Task<IActionResult> AddPersonalSolution()
        {
            var categories = await _solutionApiClient.GetAllCategoriesAsync();
            ViewBag.Categories = categories.Data;
            return View();
        }

        /// <summary>
        /// Запрос к апи на добавление решения по нашей спецификации
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        [Route("addPersonalPanel")]
        public async Task<IActionResult> AddPersonalSolution(PersonalSolutionModel model)
        {
            model.UserId = User.Claims.FirstOrDefault(c => c.Type.Contains("nameidentifier")).Value;
            NewSolutionDto dto = new NewSolutionDto 
            { 
                UserId = model.UserId,
                Name = model.Name,
                Description = model.Description,
                CategoryId = model.CategoryId,
                Cloud = new NewCloudDto 
                {
                    Name = model.CloudName,
                    Url = model.CloudUrl
                }
            };
            List<NewPhotoDto> photoList = new List<NewPhotoDto>();

            var ph = model.Logo;
            byte[] p1 = null;
            using (var fs1 = ph.OpenReadStream())
            using (var ms1 = new MemoryStream())
            {
                fs1.CopyTo(ms1);
                p1 = ms1.ToArray();
            }

            photoList.Add(new NewPhotoDto { Data = p1, Type = "Logo" });

            foreach (var photo in model.Photos)
            {
                p1 = null;
                using (var fs1 = photo.OpenReadStream())
                using (var ms1 = new MemoryStream())
                {
                    fs1.CopyTo(ms1);
                    p1 = ms1.ToArray();
                }

                photoList.Add(new NewPhotoDto { Data = p1, Type="Description" });
            }
            dto.Photos = photoList.ToArray();

            var response = await _solutionApiClient.AddSolutionAsync(dto);

            long id = response.Data.Id;

            return Redirect($"~/Product/{id}");
        }

        /// <summary>
        /// Страница добавления с помощью докер контейнера
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("addDocker")]
        public async Task<IActionResult> AddDocker()
        {
            var categories = await _solutionApiClient.GetAllCategoriesAsync();
            ViewBag.Categories = categories.Data;
            return View();
        }

        /// <summary>
        /// Запрос к апи на добавление решения с помощью докера
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("addDocker")]
        public async Task<IActionResult> AddDocker(DockerSolutionModel model)
        {
            model.UserId = User.Claims.FirstOrDefault(c => c.Type.Contains("nameidentifier")).Value;
            NewSolutionDto dto = new NewSolutionDto
            {
                UserId = model.UserId,
                Name = model.Name,
                Description = model.Description,
                CategoryId = model.CategoryId,
                Cloud = new NewCloudDto
                {
                    Name = model.CloudName,
                    Container = new NewDockerImageDto { Image = model.DockerUrl}
                }
            };
            List<NewPhotoDto> photoList = new List<NewPhotoDto>();

            var ph = model.Logo;
            byte[] p1 = null;
            using (var fs1 = ph.OpenReadStream())
            using (var ms1 = new MemoryStream())
            {
                fs1.CopyTo(ms1);
                p1 = ms1.ToArray();
            }

            photoList.Add(new NewPhotoDto { Data = p1, Type = "Logo" });

CloudJ/CloudJ.Client/Controllers/StoreController.cs
using CloudJ.Client.Clients;
using CloudJ.Client.Models;
using CloudJ.Contracts.DTOs.OrderDtos;
using CloudJ.Contracts.DTOs.SolutionDtos.Solution;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CloudJ.Client.Controllers
{
    [Controller]
    [Route("[controller]")]
    public class StoreController : Controller
    {
        private readonly IBillingApiClient _billingApiClient;
        private readonly ISolutionApiClient _solutionApiClient;
        
        public StoreController(IBillingApiClient billingApiClient, ISolutionApiClient solutionApiClient)
        {
            _billingApiClient = billingApiClient;
            _solutionApiClient = solutionApiClient;
        }

        /// <summary>
        /// Пополнить баланс(форма ввода карты)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> FillBalance(double balance)
        {
            return View(new BalanceModel { BalanceValue = balance});
        }

        /// <summary>
        /// Запрос к апи на пополнение баланса
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> FillBalance(BalanceModel model)
        {
            string userid = User.Claims.FirstOrDefault(c => c.Type.Contains("nameidentifier")).Value;
            var response = await _billingApiClient.GetBalanceByFilterAsync(new BalanceFilter { UserId = userid});

            if(response.Data?.FirstOrDefault() == null)
            {
                var resp = await _billingApiClient.AddBalanceAsync(new NewBalanceDto { UserId = userid, BalanceValue = model.BalanceValue });
            }
            else
            {
                var resp = await _billingApiClient.UpdateBalanceAsync(new UpdateBalanceDto { UserId = userid, BalanceValue = model.BalanceValue + response.Data.FirstOrDefault().BalanceValue});
            }
            
            return Redirect("~/");
        }

        /// <summary>
        /// Запрос к апи на покупку решения
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("makeOrder")]
        public async Task<IActionResult> MakeOrder(NewOrderDto dto)
        {
            var solutionResponse = await _solutionApiClient.GetByFilterAsync(new SolutionFilter { SolutionId = dto.SolutionId });
            var sol = solutionResponse.Data.FirstOrDefault();
            var plan = sol.Plans.Where(p => p.Id == dto.PlanId).FirstOrDefault();
            dto.CustomerId = User.Claims.FirstOrDefault(c => c.Type.Contains("nameidentifier")).Value;
            var balanceResponse = await _billingApiClient.GetBalanceByFilterAsync(new BalanceFilter { UserId = dto.CustomerId });
            var balance = balanceResponse.Data.FirstOrDefault();
            if (balance.BalanceValue < plan.Price)
                return Redirect("~/Home/Login");
            var response = await _billingApiClient.AddOrderAsync(dto);
            if (response.HasErrors)
                return View("Error", new ErrorViewModel { RequestId = "Ошибка при обработке заказа" });

            
            
            
            
                await _billingApiClient.UpdateBalanceAsync(new UpdateBalanceDto { UserId = dto.CustomerId, BalanceValue = balance.BalanceValue - plan.Price });
            
            return Redirect("~/Home/Login");
        }

        /// <summary>
        /// Пополнение баланса (форма ввода кол-ва денег на пополнение)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("up")]
        public async Task<IActionResult> UpBalance()
        {
            return View();
        }


    }
}

CloudJ/CloudJ.Client/Views/Product/AddCategory.cshtml
@{
    ViewData["Title"] = "AddCategory";
}
@using CloudJ.Contracts.DTOs.SolutionDtos.Category
@model CloudJ.Client.Models.NewCategoryModel

    <section class="intro intro__marg">
        <div class="container">
            <h1>Категории</h1>
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">

                        @foreach (CategoryDto c in ViewBag.Categories)
                        {
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-6">
                                    <h2 class="category__h2" style="text-align: left;">@c.Name</h2>
                                    <p class="category__p" style="text-align: left;">
                                        @c.Description
                                    </p>
                                    <p><a href="~/Product/editCategory?id=@c.Id">Редактировать </a><a href="~/Product/deleteCategory?id=@c.Id" style="color: red;">Удалить</a></p>
                                </div>
                                <div class="col-lg-2">
                                    @if (c.Logo != null)
                                    {
                                        <img src="data:image/jpeg;base64,@Convert.ToBase64String(c.Logo.Data)" style="width: 170px" class="img__center">
                                    }
                                    else
                                    {
                                        <img src="~/img/DB.png" class="img__center">
                                    }
                                </div>
                            </div>
                        </div>
                        }

                    </div>
                    
                </div>
                <div class="col-lg-6">
                    <form method="post" asp-controller="Product" asp-action="AddCategory" enctype="multipart/form-data">
                        <fieldset>
                            <div class="form-group">

                                <label asp-for="ParentCategoryId">Родительская категория</label>
                                <select size="10" class="form-control" id="ParentCategoryId" name="ParentCategoryId" asp-for="ParentCategoryId">
                                    @foreach (CategoryDto cat in ViewBag.Categories)
                                    {
                                        @if (cat.ParentCategory != null)
                                        {
                                            <option value="@cat.Id">@cat.ParentCategory.Name -> @cat.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@cat.Id">@cat.Name</option>
                                        }
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Name" for="exampleInputEmail1">Название</label>
                                <input asp-for="Name" type="theme" class="form-control" id="exampleInputEmail1"
                                       aria-describedby="emailHelp" placeholder="Введите название">
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" for="exampleTextarea">Описание</label>
                                <textarea asp-for="Description" class="form-control" id="exampleTextarea" rows="3"></textarea>
                            </div>
                            <div class="form-group">
                                <label asp-for="Logo">Логотип</label>
                                <input type="file" class="form-control-file" placeholder="Логотип" asp-for="Logo" autocomplete="off">
                            </div>

                        </fieldset>
                        <button type="submit" class="btns btn-primary rounded-0">Добавить</button>
                    </form>
                    
                </div>
            </div>

        </div>
    </section>

CloudJ/CloudJ.Client/Views/Product/AddLink.cshtml
@{
    ViewData["Title"] = "AddLink";
}

@using CloudJ.Contracts.DTOs.SolutionDtos.Solution
@model CloudJ.Contracts.DTOs.SolutionDtos.Solution.NewSolutionLinkDto

    <section class="intro intro__marg">
        <div class="container">

            
            <div class="row">
                <div class="col-lg-6">
                    <form asp-controller="Product" asp-action="AddLink">
                        <fieldset>
                            <div class="form-group">
                                
                                <div>

                                    <div class="input-group">
                                        <input hidden="true" asp-for="SolutionId" value="@Model.SolutionId" />
                                        <input asp-for="Name" type="text" class="form-control" placeholder="Название ссылки" value="" />
                                        <input asp-for="Url" type="text" class="form-control" placeholder="Url" value="" />
                                        <button type="submit" class="input-group-addon btn btn-outline-primary rounded-0">Добавить</button>
                                    </div>
                                </div>
                                <label for="exampleInputPassword1" style="margin-top: 10px;">Список всех ссыллок</label>
                                <table>
                                    <colgroup>
                                        <col span="2">
                                        <col>
                                    </colgroup>
                                    <tr>
                                        <th>Название</th>
                                        <th>Ссылка</th>
                                        <th>Удаление</th>
                                    </tr>
                                    @foreach (SolutionLinkDto l in ViewBag.Links)
                                    {
                                    <tr>
                                        <td>@l.Name</td>
                                        <td><a href="@l.Url">@l.Url</a></td>
                                        <td><a href="~/Product/deleteLink?solutionid=@Model.SolutionId&id=@l.Id">Удалить</a></td>
                                    </tr>
                                    }

                                    
                                </table>
                            </div>
                        </fieldset>
                    </form>

                </div>


            </div>

        </div>
    </section>

CloudJ/CloudJ.Client/Views/Product/AddSolution.cshtml
@{
    ViewData["Title"] = "AddSolution";
}

    <section class="intro intro__marg">
        <div class="container">
            <h1>Добавление нового решения</h1>
            <p>Способ размещения</p>
            <div class="row">
                <div class="col-lg-6">
                    <form action="add.html">
                        <button type="submit" class="btn btn-outline-primary rounded-0" asp-controller="Product" asp-action="AddPersonalSolution">По нашей спецификации</button>
                    </form>
                </div>
                <div class="col-lg-6">
                    <form action="add_docker.html">
                        <button type="submit" class="btn btn-outline-primary rounded-0" asp-controller="Product" asp-action="AddDocker">Docker</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

CloudJ/CloudJ.Client/Views/Product/GetProductById.cshtml
@{
    ViewData["Title"] = "GetSolutionById";
}
@using CloudJ.Contracts.DTOs.SolutionDtos.Review
@using CloudJ.Contracts.DTOs.SolutionDtos.Plan
@using CloudJ.Contracts.DTOs.SolutionDtos.Solution
@model CloudJ.Contracts.DTOs.SolutionDtos.Solution.SolutionDto

    <section class="intro intro__marg">
        <div class="container">

            <div class="row">
                <div class="col-lg-2">

                    @{
                        byte[] logo = Model.Photos.Where(p => p.Type.Equals("Logo")).FirstOrDefault()?.Data;
                    }
                    @if (logo != null)
                    {
                        <img src="data:image/jpeg;base64,@Convert.ToBase64String(logo)" style="width:100%" class="mt-1 product__img" alt="Large">
                    }
                    else
                    {
                        <img src="~/img/DB.png" style="width:100%" class="mt-1 product__img" alt="Large">

                    }




                    <button type="button" class="btn btn-primary mt-3 rounded-0" data-toggle="modal"
                            data-target="#exampleModalCenter">
                        Получить
                    </button>
                    <button type="button" class="btn btn-outline-primary rounded-0">В избранное</button>
                    <p>
                        <b>Категории</b>
                        <br>

                        <a href="marketplace.html">@Model.Category.Name</a>
                        @if (Model.SolutionLinks.Length > 0)
                        {


                            <br>
                            <b>Ссылки</b>
                            <br />
                            @foreach (SolutionLinkDto l in Model.SolutionLinks)
                            {
                                <a href="@l.Url">@l.Name</a>
                                <br />
                            }
                        }
                    </p>
                </div>
                <div class="col-lg-10">
                    <h1>@Model.Name</h1>

                    <div class="row">
                        <p>Рейтинг: @Model.Rate.0</p>
                    </div>
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#view">Обзор</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#comment">Отзывы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#plan">Планы</a>
                        </li>

                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade active show" id="view">

                            <p>
                                @Model.Description
                            </p>
                        </div>
                        <div class="tab-pane fade" id="comment">


                            <form method="post" asp-controller="Product" asp-action="AddReview">

                                <fieldset>
                                    <input hidden="true" name="SolutionId" value="@Model.Id" />
                                    <div class="form-group">
                                        <h6>Оценка: </h6>
                                        <input name="Rate" type="number" id="solrate" asp-for="Rate"
                                               min="0" max="5">

                                    </div>
                                    <div class="form-group">
                                        <label for="exampleTextarea">Отзыв</label>
                                        <textarea name="Text" class="form-control" id="exampleTextarea" rows="3"></textarea>
                                    </div>

                                </fieldset>

                                <div class="row mt-1">
                                    <div class="col-lg-3">
                                        <button type="submit" class="btn btn-primary rounded-0"
                                                style="margin-bottom: 30px;">
                                            Добавить
                                        </button>
                                    </div>


                                </div>
                            </form>




                            @foreach (ReviewDto r in Model.Reviews)
                            {
                                <hr />





                                <div class="row" style="margin-bottom: 10px;">
                                    <div class="col-3">
                                        <div class="row">
                                            <p class="col-2-otzuv">Оценил на @r.Rate.0</p>
                                            <p class="col-2-otzuv">@r.PostedTime.ToString()</p>
                                            <p class="col-2-otzuv">Пользователь CloudJ</p>
                                        </div>
                                    </div>
                                    <div class="col" style="word-break: break-all;">
                                        <p class="tab-pane-p" style="margin-top:-12px;">@ViewBag.ReviewAuthors[r.AuthorId]</p>
                                        <p class="tab-pane-p-2">
                                            @r.Text
                                        </p>
                                    </div>
                                </div>



                            }


                        </div>
                        <div class="tab-pane fade active" id="plan">
                            @foreach (PlanDto p in Model.Plans)
                            {
                                <div class="row col__plan align-items-center">
                                    <div class="col-lg-2 plan__p">@p.Name</div>
                                    <div class="col-lg-2 plan__p">@p.Time</div>
                                    <div class="col-lg-2 ml-auto plan__p">@p.Price</div>
                                    <div class="col-lg-2">
                                        <button type="button" class="btn btn-primary rounded-0 plan__btn">Получить</button>
                                    </div>
                                </div>
                            }


                        </div>

                    </div>
                </div>
            </div>
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
                    <div class="modal-content">

                        <div class="modal-body">
                            <h1>Выберите план</h1>


                            @foreach (PlanDto p in Model.Plans)
                            {
                               


                                <div class="row justify-content-center">
                                    <div class="col-lg-11">
                                        <div class="row col__plan align-items-center">
                                            <div class="col-lg-2 plan__p">@p.Name</div>
                                            <div class="col-lg-5">
                                                <div style="word-break: break-all;">
                                                    @p.Description

                                                </div>
                                            </div>
                                            <div class="col-lg-2 plan__p">@p.Time</div>
                                            <div class="col-lg-1 ml-auto plan__p">@p.Price</div>
                                            <div class="col-lg-2">
                                                <form method="post" asp-controller="Store" asp-action="MakeOrder">
                                                    <input name="PlanId" value="@p.Id" hidden="true">
                                                    <input name="SolutionId" value="@Model.Id" hidden="true">
                                                    <button type="submit"
                                                            class="btn btn-primary rounded-0 plan__btn"
                                                            style="width: 100%;">
                                                        Купить
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            }







                        </div>

                    </div>
                </div>
            </div>
            
</section>